version: '3'

services:
  fenics:
    image: quay.io/fenicsproject/stable:current
    volumes:
      - .:/home/fenics/shared
    working_dir: /home/fenics/shared
    tty: true
  
  result_processing:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./ResultsDir:/app/ResultsDir
      - ./ProcessResults.py:/app/ProcessResults.py
